### PR TITLE
Adds CheckmarkCircle, Megaphone, PresentationChart, Stopwatch icons

### PR DESCRIPTION
**Pull request by BrettBukowski**
screen shot 2016-03-04 at 2 56 38 pm

screen shot 2016-03-04 at 2 56 49 pm

screen shot 2016-03-04 at 2 56 58 pm

screen shot 2016-03-04 at 2 57 09 pm

### CODE REVIEW

**Comment by BrettBukowski** [comment]
ping

**Comment by kevzettler** [comment]
lgtm

**Comment by cohitre** [comment]
ping.

**Comment by cohitre** [comment]
ping

**Pull request merged**
